### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by BeatJuice5** [sc1341/InstagramOSINT#1]
Could you maybe explain how to use it?

**Comment by p0lux** [comment]
Can you put a requirements.txt ?

**Comment by Hoggmeiser** [comment]
I had to futz with it, but I got it working on my windows machine.

-Need at least Python 3.7 (maybe even 3.6 works)
-Install the BeautifulSoup4 module
    -command line "pip install beautifulsoup4"
-Install Requests module
    -command line "pip install requests"
-From command line...
    -"python .../main.py --username xxxxxxx"

**Comment by SkyHawkB** [comment]
Yeah just install dependencies and run it. A note on the arg format would be good though.

**Comment by sc1341** [comment]
Hey guys! I'll make a requirements.txt file! I didn't think people would actually use this! I'll get right on some of these issues! Thanks for bringing up these issues!

**Comment by sc1341** [comment]
The usage has been updated in the README.md.

Thanks for the feedback!
