### ISSUE TITLE
how to fix this error?

### ISSUE THREAD

**Issue by snrlxx** [sc1341/InstagramOSINT#14]
python3 main.py 
  File "main.py", line 50
    print(colors.OKGREEN + f"[*] Starting Scan on {self.username}" + colors.ENDC)
                                                                 ^
SyntaxError: invalid syntax

**Comment by sc1341** [comment]
Hi there!

Please make sure you are using a Python version that is greater than or equal to 3.6. 

This is due to the use of “f-strings” in the script. 

Thank you!
