### ISSUE TITLE
Wont get all images

### ISSUE THREAD

**Issue by Aspiringpentester** [sc1341/InstagramOSINT#17]
I used this tool (with --downloadPhotos) on someone with ~70 posts, but it only downloaded 11. Is there a reason for this?

**Comment by YnwaFawzy** [comment]
@Aspiringpentester is there any error message showing up ?

**Comment by Aspiringpentester** [comment]
No

**Comment by Aspiringpentester** [comment]
I just now used another post scraping tool, and this time it downloaded 12 posts, but still not all 70. I think this is a thing wrong with Instagram, but if anyone has a solution I'd like to hear it.

**Comment by YnwaFawzy** [comment]
@Aspiringpentester I'll check it when I'm back home ,but did you try to change the user agent in the tool ?

**Comment by Aspiringpentester** [comment]
To be honest, I'm really a programmer, just interested in code. I don't really know what you mean.

**Comment by YnwaFawzy** [comment]
@Aspiringpentester no problem , I'll check it and update you :)

**Comment by YnwaFawzy** [comment]
@Aspiringpentester 
ok ,so I was testing it ,and apparently if you open any profile on the web version on Instagram,it will only show the last 16 posts ,it won't show you more even if you scroll down.

this will limit the program to show maximum 16 images. 

you can confirm that by going to that person's profile on the browser without logging in,and you should see the 14 images and two videos(probably igtv).

to show more images ,we need to imitate a click on "show more posts from xxxxxx",then get the maxim number of images allowed by insta.

I'll probably try to do that next weekend in case I have free time.

**Comment by Aspiringpentester** [comment]
Ok thanks.

**Comment by Aspiringpentester** [comment]
Has there been any updates regarding this issue?

**Comment by YnwaFawzy** [comment]
aaaaaaand I forgot about it xDDDD.

my apologies ,I'll try to finish it within this week ,I'll set a reminder XD

**Comment by Aspiringpentester** [comment]
Ok thanks.

**Comment by YnwaFawzy** [comment]
@Aspiringpentester Hi , apologies for being veryyyyy late , i had few things working on , anyway ,i've checked the code and sadly it can not be modified to get the images dynamically as it's using very simple fetching technique instead of using headless browser and interacting with the page , but there sure is another programs on github that can achieve that , i didn't research on them tbh

**Comment by Aspiringpentester** [comment]
@YnwaFawzy Ok. I guess I'll look into it then.

**Comment by chris-greening** [comment]
@Aspiringpentester did you end up finding a tool that did what you were looking for?

**Comment by Aspiringpentester** [comment]
@chris-greening I actually haven't looked into it lol. I don't really have any interest in finding one tbh.
