### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by p0lux** [sc1341/InstagramOSINT#2]
Can you create a requirements.txt to easily install all dependencies
Thank's !

**Comment by SkyHawkB** [comment]
It's only BeautifulSoup4 and requests. You can easily install it manually. However, a requirements.txt would be nice.

**Comment by sc1341** [comment]
Gladly! I am working on it right now along with a few other changes.

Thanks for bringing this up!

**Comment by sc1341** [comment]
Just added it!

Thanks!
