### ISSUE TITLE
Instagram OSINT does not work

### ISSUE THREAD

**Issue by ghost** [sc1341/InstagramOSINT#23]
It keeps saying user not found or it gives me a random syntax error

**Comment by kalixxs** [comment]
A mi igual hay alguna solución?

**Comment by CollenMenezes** [comment]
Same.

**Comment by nuno-carvalho** [comment]
The same.
It could be a great tool if it works

**Comment by nathanpittman8** [comment]
Yeah same with me. This doesn't work at all

**Comment by CrilleH** [comment]
Doesn´t work, no respomse at all more than user not found
